### ISSUE TITLE
use .zenodo.json

### ISSUE THREAD

**Issue by rubenarslan** [FelixHenninger/lab.js#10]
This way, when I import your Zenodo pages into Paperpile, I automatically get the correct metadata. See [here](https://github.com/rubenarslan/paternal_age_fitness/blob/master/.zenodo.json) for an example.

**Comment by FelixHenninger** [comment]
This is a great idea, thank you! I'll add the metadata file over the weekend.

Do you know whether there is a more general metadata format (i.e. not limited to zenodo only)? We recently added the ability to collect metadata for every study, it would be cool to export this in a standardized way.

**Comment by rubenarslan** [comment]
Can you clarify what you mean? I'm currently looking into metadata for formr study codebooks with the help of @der-bruemmer

**Comment by FelixHenninger** [comment]
Ah, sorry, I was wondering whether there was a metadata standard that worked outside of zenodo for a more long-term solution &ndash; a quick search turned up [Codemeta](https://github.com/codemeta/codemeta), which looks [like this](https://github.com/codemeta/codemeta/blob/master/codemeta.json).

Maybe that might be useful for codebooks, too?

**Comment by der-bruemmer** [comment]
If you look at codemeta, most of the [Terms](https://codemeta.github.io/terms/) are taken from https://schema.org, a large metadata initiative supported by most of the large search engines. So these attributes are widely supported and are good candidates for general metadata project level, describing authors, repositories, versions etc. For more specific codebook related metadata: datasets, items, codes and the like, some of it can be covered by vocabularies like [DCAT](https://www.w3.org/TR/vocab-dcat/) and [CSVW](https://w3c.github.io/csvw/syntax/), but specifically on item level, there seems to be a gap in the current landscape of metadata description.

Generally, I would recommend supporting large repositories in their native format and adding a more general metadata standard like schema.org as well. We may see wrappers that offer automatic conversion at some point, but the field is still too fragmented for that.

**Comment by FelixHenninger** [comment]
@der-bruemmer Thanks a lot for the clarification! I have to admit that I know very little about the metadata initiatives -- do you know of a repository that uses schema.org / codemeta? Is there a validation tool available? If you have a momemt, can you recommend a resource/paper where I might read up on all of these developments?

@rubenarslan I've tried to add a [.zenodo.json](https://github.com/FelixHenninger/lab.js/blob/master/.zenodo.json) to the project, hope this works for you (might need another release to zenodo, which will hopefully come early in the new year). If you are more familiar with this format than I am, how would you represent our mix of licences (Apache 2.0 / AGPL) in the `license` field? I'm a bit unhappy that this defaults to `cc-by` :-/ .

**Comment by FelixHenninger** [comment]
@der-bruemmer @rubenarslan What do you guys think about the [Citation File Format](https://citation-file-format.github.io/1.0.3/specifications/)?

**Comment by FelixHenninger** [comment]
Ok, closing this for now, the proximate issue being solved, would be happy to discuss this further!

**Comment by rubenarslan** [comment]
@FelixHenninger yes we'll keep you in the loop what end up doing and discover about metadata. and we should still exchange experiences about formr and lab.js at some point :-)

**Comment by FelixHenninger** [comment]
@rubenarslan Awesome, thanks! And regarding `formr`, I'd love to chat -- we're thinking about integration in questionnaire-oriented tools right now, and yours would be a natural fit. I've made a note to revisit this at the end of the semester at the latest, if it suits you earlier, please don't hesitate to let me know, I'd be glad to discuss things!

**Comment by FelixHenninger** [comment]
Ok, this is a bit late, but for the record -- I just added a [CFF](http://citation-file-format.github.io/)-Style [citation file](https://github.com/FelixHenninger/lab.js/blob/master/citation.cff). I hope that's going to cover all metadata needs for a bit 😄.

**Comment by rubenarslan** [comment]
Just a small note: The Zenodo DOI you recommend on your Github page still has outdated metadata.

**Comment by FelixHenninger** [comment]
Thanks! The metadata is in the repo, but it turns out that I haven't made an official release via GitHub since I added it more than a year ago 😳 (we run a more rolling-release schedule because so much is going on and I'm too disorganized). I'm finishing things up right now for a new release, so please expect this to (hopefully) be solved automatically in the near future.

In fact, even the citation in the readme is not up-to-date, as Ulf and Yury have switched positions, the latest order of authors is:
> Henninger, F., Shevchenko, Y., Mertens, U. K., & Hilbig, B. E. (2018). lab.js: Browser-based behavioral research. doi: 10.5281/zenodo.597045

Btw, I haven't forgotten you, but I kinda crashed before Christmas and had to take things a bit more slowly, please expect communication very soon!

**Comment by FelixHenninger** [comment]
Ok, I just updated everything. Thanks for the heads-up, I hope things are more useful now!
