### ISSUE TITLE
Missing video instructions on embedding in Qualtrics

### ISSUE THREAD

**Issue by maryclarecc** [FelixHenninger/lab.js#106]
Hello! I am working with lab.js for the first time and would like to embed the experiment in Qualtrics. However, the videos are no longer available at this link: [https://labjs.readthedocs.io/en/latest/learn/deploy/3a-qualtrics.html](https://labjs.readthedocs.io/en/latest/learn/deploy/3a-qualtrics.html) 

Are the videos perhaps available somewhere else? This is my first time embedding things in Qualtrics so I do not want to screw anything up. Thanks!

**Comment by FelixHenninger** [comment]
Hi @maryclarecc , and thanks a lot for bringing this to our attention! 

The videos seem to work from here, so I did a little sleuthing -- could it be that you're using Safari? It looks that has some [issues with the file codec](https://caniuse.com/webm) the videos come in. If you could check with Firefox or Chrome, I think the videos should work; as a backup, you could try downloading the files and opening them in a media player such as [VLC](https://www.videolan.org/vlc/), that might also help.

I'll look into alternate formats, it looks like Safari is a bit particular about what it will play. Thanks again for raising this issue!

-Felix

**Comment by maryclarecc** [comment]
Hello! Thank you for your quick response. I was using Chrome on my Windows computer and I was able to watch all other videos and create the experiment. The Qualtrics instruction page was my last step and those were the only videos that don’t work. I tried to download them but it is showing up with a black box and a crossed out arrow in it, and it is not clickable. 

MaryClare C. Colombo

On Sep 21, 2020, at 08:19, Felix Henninger <notifications@github.com> wrote:

﻿
Hi @maryclarecc , and thanks a lot for bringing this to our attention!

The videos seem to work from here, so I did a little sleuthing -- could it be that you're using Safari? It looks that has some issues with the file codec the videos come in. If you could check with Firefox or Chrome, I think the videos should work; as a backup, you could try downloading the files and opening them in a media player such as VLC, that might also help.

I'll look into alternate formats, it looks like Safari is a bit particular about what it will play. Thanks again for raising this issue!

-Felix
