### ISSUE TITLE
Broken links on the website

### ISSUE THREAD

**Issue by carolfs** [FelixHenninger/lab.js#112]
On the "Resources" menu of the lab.js.org website, there are two broken links to "Performance" and "Publications". Clicking on "Performance", for example, the address is https://resources/performance/ rather than https://lab.js.org/resources/performance/ (the correct address).

Using Chrome 87.0.4280.67 and Firefox 78.5.0esr on Mac OS X.

This is the code and the problem is probably those `&#x2F;` characters.

```
                  <a class="dropdown-item" href="/&#x2F;resources&#x2F;performance&#x2F;">
                    Performance
                  </a>
                
              
                
                  <a class="dropdown-item" href="/&#x2F;resources&#x2F;publications&#x2F;">
                    Publications
                  </a>
```

**Comment by FelixHenninger** [comment]
Hi @carolfs, thanks a lot for pointing us to this issue -- I wouldn't have noticed otherwise! 😅 I think things should be working now. Thanks again for reaching out, and many kind regards,

-Felix
