### ISSUE TITLE
Add utility for getting the current component from a sequence.

### ISSUE THREAD

**Issue by jdpigeon** [FelixHenninger/lab.js#183]
With the flow control update, it seems possible to get a reference to the current loaded Component. However, it's a bit of an arcane invocation that should probably be addressed by a utility method attached to the base `Sequence` class.

Currently we are able to fetch the current sequence (in a Plugin applied to the top-level Sequence) with the following:
`const currentComponent = this.context?.internals.controller.currentStack.slice(-1)[0] as core.Component;`

@FelixHenninger, what do you think about this? Could we make it a little easier to get the current component, and ensure the correct type is returned?

**Comment by FelixHenninger** [comment]
Hej @jdpigeon, what do you think of `currentLeaf` as an accessor name?

**Comment by FelixHenninger** [comment]
Added as `base.Controller.currentLeaf` as of 52248431b940f01703fbe0fc29ce0dce1fd316e9 . I'm closing this for now, but happy to discuss and change naming. Thanks again for the excellent suggestion!
