### ISSUE TITLE
Clarify / add hint to responses UI

### ISSUE THREAD

**Issue by FelixHenninger** [FelixHenninger/lab.js#2]
In the `lab.js` builder interface, small hint components provide additional frequently-used information where it might be needed, so that users don't need to look up things in the documentation too often. Right now, these hints are not as frequent as they could be, and one area where they are missing is the part of the UI where users define the responses available to participants. For example:

* It is not entirely clear what the `filter` and `target` fields are for.
* Similarly, the use of the `label` field is not directly apparent.

These questions are covered in the documentation:

* [UI tutorial: Adding responses](https://labjs.readthedocs.io/en/latest/learn/builder/3-responses.html#collecting-responses)
* [Code reference: The `responses` option](https://labjs.readthedocs.io/en/latest/reference/core.html#options.responses)

Your mission, should you choose to accept it, would be to add the most important parts of this information to the builder UI. A hint would be a great help to many users -- should you find a way to improve the UI along the way, you are in no way limited to the hint alone.

**Comment by pvskarthikeya** [comment]
Hi! Can I start working on this?

**Comment by FelixHenninger** [comment]
Hi @pvskarthikeya &mdash; wow, many thanks for stopping by and offering to join! You're super-welcome to give this a go, and any help is very much appreciated.

I must admit that I haven't yet finished the contributor documentation, so things are not as well organized as they should be. We have some information on the [project layout and build steps](https://labjs.readthedocs.io/en/latest/meta/contribute.html), but please don't hesitate to reach out if there is anything I can do to help you get started.

You can always reach me in the [project slack channel](https://slackin-nmbrcrnchrs.herokuapp.com/), but I'll also watch the issues more closely, so feel free to post here if you have questions or suggestions.

Again, a huge thanks for considering to contribute!

**Comment by pvskarthikeya** [comment]
@FelixHenninger Awesome. I am still reading the documentation. I will let you know if i have any questions? Thank you. 😃

**Comment by FelixHenninger** [comment]
Absolutely, please do! Also, if you run into anything that could be clearer, do let me know &mdash; I'm happy to explain things and always looking for ways to improve the docs.

**Comment by FelixHenninger** [comment]
This is fixed in d63532ee05dda7a98aac0dba82dbc20265e936dd . Thanks @pvskarthikeya for your help and continuous support!
