### ISSUE TITLE
Study stuck in loading in the preview mode in lab.js

### ISSUE THREAD

**Issue by MariaPiresCoelho** [FelixHenninger/lab.js#229]
### What would you like or expect to see?
I created my experiment in Builder. I have a task where 4 different images and text are shown through a loop with 4 iterations. 

### What is currently happening?
My preview mode says "_Loading experiment. The experiment is loading and should start in a few seconds_". But it does not update to the task, it gets stuck in this screen.

### Finally, please tell us which browser you're using (and the version thereof)
I have tried running it on Chrome (version: 121.0.6167.189, Official Build, 64-bit)  and Microsoft Edge (version: 122.0.2365.52, Official Build, 64-bit). 

Thank you very much in advance for your assistance. 

Sincerely, 
Maria Coelho

**Comment by MariaPiresCoelho** [comment]
Hiello again!

I believe my loading error in the preview mode may be linked to the images. 

I tried to go through every step of the study creation again (and previewing in every step) and it gets stuck when I add the images within the loop while calling the parameters.image. 

Can anyone help me?

Thank you very much, 

Maria Pires Coelho

**Comment by mcfarla9** [comment]
Have you tried making a study that simply shows one of your image files, without using a Loop?

**Comment by MariaPiresCoelho** [comment]
Hello!

I have just figured out what the error was. Within the loop I called for the parameter image in ${ this.files[this.parameters.image] } but the s in parameters was missing, and that is why the study would not load in preview mode. 

Thank you, mcfarla9, for your reply!
