### ISSUE TITLE
Builder exports outdated static files / overcaches library

### ISSUE THREAD

**Issue by AlexandraSchenker** [FelixHenninger/lab.js#32]
### What would you like or expect to see?
Running an experiment generated by PHP Export  (several times over the last days) does not run (stuck on: "Loading Experiment
The experiment is loading and should start in a few seconds."

### What is currently happening?
Experiment is stuck on "Loading Experiment. The experiment is loading and should start in a few seconds."

An older PHP export (mid of September 2018) does run fine.

### Please describe the steps needed to reproduce this phenomenon
I believe that this would happen with any PHP Export right now: Save, chose Generic webhost (PHP backend), upload it on our server, adjusting the rights for the data directory.

I can attach a print screen of an error in the debug window.

### Finally, please tell us which browser you're using (and the version thereof)
Firefox, Google chrome, IE (on Windows 10).

**Comment by AlexandraSchenker** [comment]
![inked2019-jan-load-experiment-problem-php_li](https://user-images.githubusercontent.com/44519729/52008251-897d5280-24d0-11e9-9fbf-d23ed815cf9f.jpg)

**Comment by FelixHenninger** [comment]
Hej @AlexandraSchenker,

thanks a lot for your bug report, and sorry things aren't working! I'm currently traveling, but I'll have a look at this tonight -- in the meantime, would you like to come over to the [`lab.js` support channel](http://slackin-nmbrcrnchrs.herokuapp.com/) so we can take a closer look at this together?

I'll be available there, but I'll update the issue here if I figure something out in the meantime.

**Comment by FelixHenninger** [comment]
Ok, so I've just tried the export, and it seems to work for me™ -- of course, that doesn't need to mean much. Would it be possible to share your study (via some other medium if you'd prefer not to have it public)?

I'd love to take a closer look at this -- obviously this is the type of bug I'd love to squash ASAP. Thanks again for reporting it, and sorry for the trouble!

**Comment by FelixHenninger** [comment]
Just a quick update for repository housekeeping: We both took a close look at this in the support channel yesterday, and it seems that the builder interface is supplying an old version of the library, but with up-to-date study code. By re-loading the builder or switching to a different browser, the study works again. It also seems to export the offline version correctly. 

This is somewhat strange, and I'm going to investigate the inconsistency further.

**Comment by AlexandraSchenker** [comment]
Hi Felix, I can confirm that I tested with Firefox as discussed above  (new import of json on different browser) and the PHP experiment is loading with the correct library version and runs.

Though we still have these in the private chat mentioned performance issues. Our experiment only runs completely through with Firefox (352 items). The other browsers block at some point. 

Please let me know how to send through the *json file so that you could test it on your platform.

Your help is much appreciated, with best wishes, Alexandra

**Comment by FelixHenninger** [comment]
Hej Alexandra, thanks for cross-browser-checking! If you have a moment, it would be great if you could check in a Chrome private/incognito window, that (I think) circumvents any caching the browser would otherwise do, and would tell us whether this is a Chrome issue in general, or some outdated cache content that's causing trouble.

I've sent you contact details via Slack, and would be happy to take a look at your study!

**Comment by AlexandraSchenker** [comment]
Hello again Felix, I just did the test as suggested:
exported the PHP package under the follwowing condition: check in a Chrome private/incognito window and... It it loaded fine.
So I assume there was  a strange thing going on on my laptop with broswer caching with caused it to pack the old libraries... hence does not seem to be a general issue. :-)
Have a good evening, Alexandra

**Comment by FelixHenninger** [comment]
Hej, thanks a lot for checking! That does indeed sound like a caching issue. If you have a moment to help us fix it, could you open the 'Network' tab in your browser's developer tools, reload the page, and send me a screenshot of the result? (feel free to send a Slack message if you prefer) I think I'd like to get to the bottom of this 🙂

Here's what the result looks like for me:
![screenshot 2019-02-08 at 21 40 40](https://user-images.githubusercontent.com/8349942/52505038-89750500-2bea-11e9-98f5-6f76b44afc71.png)

**Comment by FelixHenninger** [comment]
And, come to think of it, it would be super-helpful if you could include the headers of the `lab.js` file in the screenshot, if that's possible -- that's the file for which the builder is giving you an outdated version.
![screenshot 2019-02-08 at 21 46 48](https://user-images.githubusercontent.com/8349942/52505237-2afc5680-2beb-11e9-982a-b9f8b4f96a6e.png)

**Comment by AlexandraSchenker** [comment]
Hello again Felix,
I re-opened the old link on Chrome which had caused the problem. Not sure if the problem remains, did not rebuild and re-test.
I created the printscreen and will send it through over the private chat. Let me know if you can see the issue or if I need to re-test if the current Chrome environment still causes the issue.
I will be happy to help.
Have a good weekend and best wishes,
Alexandra

**Comment by FelixHenninger** [comment]
Hej Alexandra,

we continued this discussion via Slack, and (if I remember correctly) kinda-solved it, at least the immediate issue (which looked like some strange browser behavior). Therefore, I'm closing this issue for now, even though I'm going to keep an eye out for similar reports. Feel free to re-open if the issue re-occurs, or if you'd like to discuss this further!

Kind regards, and all the best,


-Felix
