### ISSUE TITLE
Error in "Building a local copy" tutorial

### ISSUE THREAD

**Issue by tpronk** [FelixHenninger/lab.js#38]
When building lab.js, I noticed the output went to a dist/ instead of build/. I think that in the "Building a local copy" tutorial, the text "will output a transpiled version in the packages/library/build directory" should be "will output a transpiled version in the packages/library/dist directory"
https://labjs.readthedocs.io/en/latest/meta/contribute/build.html

**Comment by FelixHenninger** [comment]
Hej, thanks, that was my mistake! Fixed in 88446836d75ceec6354bf09761e074784ff7ae93
