### ISSUE TITLE
JATOS connection - better use jatos.startNextComponent instead of jatos.endStudy

### ISSUE THREAD

**Issue by kristian-lange** [FelixHenninger/lab.js#41]
I'd suggest to use [`jatos.startNextComponent`](http://www.jatos.org/jatos.js-Reference.html#jatosstartnextcomponentresultdata-onerror) in `lab.js/packages/builder/src/logic/io/export/modifiers/jatos.js`. The currently used `jatos.endStudy` always finishes the study - even if other JATOS components exists. On the other side `jatos.startNextComponent` starts the next component and only if there is no other component it finishes the study. This way lab.js would allow subsequent components; often users have a component with a last screen displaying some results or a confirmation code.

**Comment by FelixHenninger** [comment]
Hej Kristian, thanks so much for this great suggestion! That makes total sense, and was a total oversight on my part. This is fixed in 63856b801a73e9fbd2a392293c63c1b4b7795386, and I'll do a bit of testing on the [beta deployment](http://labjs-beta.netlify.com/); it will probably land in production over the coming weeks.

**Comment by FelixHenninger** [comment]
Ok, this looks good (not that I expected anything else 😉), so I'm closing this for now -- I really like the idea of multi-component studies, and was wondering whether we could somehow make it easier to export `lab.js` tasks as individual components, or split studies across multiple pages. I don't have a good idea regarding how to do this -- but if you do, I'd love to chat!

Thanks again for your idea, I'd love to keep improving the JATOS integration!

**Comment by kristian-lange** [comment]
Nice! Thanks! :)

**Comment by FelixHenninger** [comment]
Sure thing -- this has been the very least I can do, and I'm glad to make the integration better for everyone! Thanks a lot for your ongoing work on JATOS, we regularly hear from labs where it's made study hosting much easier and I love that ❤️. Please don't ever hesitate to let me know if I can help!
