### ISSUE TITLE
Design improved header for readme and/or project homepage

### ISSUE THREAD

**Issue by FelixHenninger** [FelixHenninger/lab.js#5]
Both the [project readme](https://github.com/FelixHenninger/lab.js/blob/master/readme.md) and the [homepage](https://felixhenninger.github.io/lab.js/) use the project logo alone as their main header image. **The header image is what people will notice first when they visit our project, and therefore it might be worthwhile making it nicer and potentially more relevant to the target audience**, for example by
* Highlighting the applications of the library in the cognitive and other sciences (the flask logo does not bear that much relation to our users)
* Underlining our goal to be friendly and accessible rather than overly technical

These are just suggestions &ndash; any **ideas, sketches, or artwork would be totally fantastic and are very welcome**! Please leave a note if you need a vector version of the logo or any other resource to get you started.

**Comment by FelixHenninger** [comment]
A few quick technical additions: 
* The header image for the readme should be around 888px wide and probably around 400 to 600px high. On the homepage, the header is 1110px wide and 400px high (you're welcome to go beyond these dimensions, though)
* Vector images would be great, but are not mandatory.
* Please make very sure that any external artwork you use is licensed so that it can be included in an open-source project.

**Comment by himankpathak** [comment]
Hey felix, i would like to help you with this designing of the header.

**Comment by FelixHenninger** [comment]
Hi there, @himankpathak, thank you so much for stopping by and pitching in! 

This is an issue where help would be especially welcome, because I'm not very good at drawing or designing in general. I think that the header images on the homepage and the readme could be more welcoming, and reflect who the software is built for &mdash; scientists studying cognition and behavior, in cognitive science, psychology, economics and other social sciences. 

How would you like to approach this, for example would you like to get started directly (maybe with some rough sketches?) or would you like to discuss ideas first? Please let me know what works best for you, and how I can help you, or stop by the slack channel. I'm looking forward to your ideas!

Kind regards, and thanks again,

-Felix

**Comment by himankpathak** [comment]
@FelixHenninger i just need a rough idea like what what things the header of readme page and homepage should include...
The things i have currently in mind :
- logo of lab.js
- "lab.js" written in some cool way
- a short tagline that would help describe the project best (suggestions needed over here)

If you have anymore suggestions, i would be happy to discuss them.

**Comment by FelixHenninger** [comment]
@himankpathak That sounds great! Here's what we have so far: The logo, I think, works fairly well already:
![rect4230](https://cloud.githubusercontent.com/assets/8349942/26531175/f3320e84-43e3-11e7-8d3c-a5ade24306d1.png)

There is a preliminary wordmark to go with it, but this could without doubt be improved apon:

![logotype_red](https://cloud.githubusercontent.com/assets/8349942/26531201/6de358f4-43e4-11e7-939b-886aa3c11759.png)

I think the logo works best in bright, solid colors like those above (I'm always tempted to put a rainbow in the background when I'm working with it).

My own ideas (with which you absolutely don't have to agree!) have centered around adding some texture around the logo to make it more friendly, more personal and maybe less sterile. Possibly a nice [gradient](https://web.archive.org/web/20170312160807/http://mrmrs.io/gradients/) would already go far, or a basic [pattern](https://www.toptal.com/designers/subtlepatterns/thumbnail-view/)?
I would love it if the header could convey that **this project is about doing science, collecting data, understanding the mind &mdash; and yet doing so in an open, transparent, friendly, collaborative, approachable way**. Technology should be about assisting the user, and should be presented in a non-intimidating way.

Including a tagline is an excellent idea! Would it be ok to start with the repository summary "Create, run and share experiments in your browser"?

Ok, so much from my side &mdash; I hope that helps and makes sense, I'm looking forward to your ideas and suggestions, and am happy to answer any further questions. Again, please make absolutely sure that your proposals can be licensed freely!

**Comment by himankpathak** [comment]
@FelixHenninger your idea of adding a gradient sounds great i was already thinking bout adding a yellowish gradient (flat yellow would look really nice).

> "Create, run and share experiments in your browser"

This tagline looks great i think it should be good to start with

**Comment by FelixHenninger** [comment]
I'm going to close this for now -- I think the current version will do for the time being. @himankpathak Thanks a lot for your support, if you'd like to take another shot at this, please do let me know!
