### ISSUE TITLE
enhance - modal : size

### ISSUE THREAD

**Issue by rbalet** [FelixHenninger/lab.js#59]
### What would you like to see?
Modals could be much bigger  (like 90vh / 90vw)

![image](https://user-images.githubusercontent.com/44493964/64260174-b1330e00-cf2a-11e9-95f3-d2b73e5abbc0.png)

**Comment by FelixHenninger** [comment]
Fixed in dc68b21e74e0ab836f6f3b08c213a9da634e794b. Thanks again for the impulse!
