### ISSUE TITLE
enhance - sidenav/footer : add link

### ISSUE THREAD

**Issue by rbalet** [FelixHenninger/lab.js#64]
_a small isssue_

### What would you like or expect to see?

could we link this button to this url ? https://lab.js.org/
![image](https://user-images.githubusercontent.com/44493964/70212039-dbb58280-1736-11ea-9585-ecfa794d9c56.png)

**Comment by FelixHenninger** [comment]
Great idea, you wanna go ahead? The code is in `src/Components/Footer/index.js`.
