### ISSUE TITLE
core - css : into scss

### ISSUE THREAD

**Issue by rbalet** [FelixHenninger/lab.js#68]
### What would you like?
Migrate the builder project into scss.

I just need your green light and I'll do it myself.

**Comment by FelixHenninger** [comment]
Hi Raphaël,

thanks a lot! We already use `SCSS` for the builder, for example we use a quite heavily modified set of bootstrap styles (see `src/components/Layout/bootstrap-custom.scss`). Many other stylesheets are much closer to raw `CSS` though. Do you see any specific points where a migration of the remaining scripts to `SCSS` would be particularly beneficial?

Best,


-Felix

**Comment by rbalet** [comment]
Hi, didn't saw that you already implemented the scss. I'm good then, sry for this issue.  
_Do you see any specific points..._ : No, was juste for myself when I was developing
