### ISSUE TITLE
Template parameters in Loop flow are not predictably defined on Screen construction

### ISSUE THREAD

**Issue by jdpigeon** [FelixHenninger/lab.js#83]
I keep running into unexpected behaviour related to template parameters in the Loop flow.

When a number of `Screens` are declared in a `Loop`, they will all be constructed when the experiment loads with the parameters defined in the template. However, it seems that they do not have the parameters that are generated for them by the `Loop` until they are run.

Is this an implementation detail that allows some more flexible runtime Loop parameterization or something? It seems to me that if the flow is being generated on experiment load, it would make sense to set the parameters there as well. The problem is when we're trying to extend the lab.js `Screen` with more complex components we keep running having to write complex parameter management code in order to make sure we're running with the correct parameters.

**Comment by FelixHenninger** [comment]
Hi Dano, and many thanks for your question!

> When a number of Screens are declared in a Loop, they will all be constructed when the experiment loads with the parameters defined in the template. However, it seems that they do not have the parameters that are generated for them by the Loop until they are run.

Almost, the way it should work is that nested components receive parameters when they are prepared.

> Is this an implementation detail that allows some more flexible runtime Loop parameterization or something?

It's the only way (I know of) to do things: I don't think it's possible that we could pass them through on construction / initialization, and even the loop parameters are not generated until the loop is prepared.

> The problem is when we're trying to extend the lab.js Screen with more complex components we keep running having to write complex parameter management code in order to make sure we're running with the correct parameters.

Could you share an example of that? I'd be happy to discuss details in context. Sorry for the frustration caused!

Kind regards, and thanks again for the feedback,


-Felix

**Comment by FelixHenninger** [comment]
(solved this in support, using the `prepare` event was the key)
