### ISSUE TITLE
lab.js integration to soscisurvey.de issue

### ISSUE THREAD

**Issue by Teletobi1986** [FelixHenninger/lab.js#91]
Dear Felix,

thank you so much for your great work. I have some trouble integrating the experiment within the survey. I use soscisurvey.de as survey software. The experiment is displayed correctly, but the event is not fired [alert("blubb") not shown]. Do you have a suggestion how to fix this error? Thank you.

Tobias

PS. Wir können auch gern auf Deutsch kommunizieren :)

```
<iframe
  src="https://tobias-kuhl.de/labjs/"
  style="width: 100%; min-height: 600px; border: none;"
></iframe>
<script>
  // Listen for the study sending data
  window.addEventListener('message', function _labjs_data_handler(event) {
alert("blubb");
    // Make sure that the event is from lab.js, then ...
    if (event.data.type === 'labjs.data') {

      // ... extract the data lab.js is sending.

      // The collected data is available via:
      // - event.data.json for json-encoded data
      // - event.data.csv for csv-formatted data
      // - event.data.raw for the raw data array
      const data = event.data.json;

      // ... process data and submit page
      // (the specific code here will depend on the tool
      // you're using to process and store the data)
      // ...
document.getElementById("LA01_01").value=data;
SoSciTools.submitPage();
      // ... finally, stop listening for further data
      window.removeEventListener('message', _labjs_data_handler)
    }
  })
</script>
```

**Comment by FelixHenninger** [comment]
Hi @Teletobi1986, and many thanks for your excellent question! I think what's going on is that the study you are hosting on your website is built for server-side data collection via the `Generic web host` export -- it's trying to store the data on your server, and isn't aware of SoSci. If you export the study via the `Generic survey tools` export instead, and replace the uploaded version, I'm pretty sure that the message should come through (you can save the data in both places, too, if you like, but that's a separate discussion :-) )

In general, please let me extend a warm invitation to join our [support channel](https://lab.js.org/resources/support/) where there's more folks around to answer questions, which usually speeds up the process dramatically (sorry for the belated response!). I try to focus the GitHub issues around technical discussions.

Ok, so much real quick -- I hope this helps, thanks for your excellent report, and again, please be warmly invited to hop onto the support channel to speed things up in the future!

All the best, and happy experimenting,


-Felix
